### ISSUE TITLE
Release the latest version to crates.io

### ISSUE THREAD

**Issue by pradt2** [nulldotblack/wireguard-nt#1]
Hi, currently the released version "0.1.0" doesn't contain any useful code. It would be good to create a new release with the latest code.

**Comment by TroyNeubauer** [comment]
Thanks for the issue! I still have yet to implement parts of the api and it is still somewhat unstable, but I will be sure to release one once #2 and #3 are fixed.

**Comment by pradt2** [comment]
Solved by #5. Closing.
