### ISSUE TITLE
adapter::set_default_route always forces all traffic through the WireGuard interface

### ISSUE THREAD

**Issue by pradt2** [nulldotblack/wireguard-nt#2]
Hi, it seems that the `adapter::set_default_route` always tries to route all traffic (not just the portion described by the `interface_addr` argument), through the interface. This means that scenarios when I would like to route a portion of the traffic through WireGuard, and another portion via another interface, are not currently possible.

**Comment by TroyNeubauer** [comment]
I overlooked this when first implementing the API. I'll fix this and get back to you

**Comment by TroyNeubauer** [comment]
My latest commit on `update-api` should fix this. Please give it a try and let me know how it goes when you have time. Also it works with wireguard-nt 0.10.1

**Comment by pradt2** [comment]
Just tested the `update-api` branch with the 0.10.1 driver and it works like a charm (tested both the driver and the routing). Thanks a lot for making these changes

**Comment by pradt2** [comment]
Solved by #5. Closing.
